<?php
/**
 * Webhook
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VonageIntegrationSuite
 *
 * __Vonage® Integration Suite__ powered by __gUnify&trade;__.  --------------------------------
 *
 * OpenAPI spec version: v1
 * Contact: gunifydevops@vonage.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace com.vonage.client.model.VonageIntegrationSuite;

use \ArrayAccess;

/**
 * Webhook Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Webhook implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Webhook';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id' => 'string',
        'user_id' => 'string',
        'account_id' => 'string',
        'url' => 'string',
        'status' => 'string[]',
        'events' => 'string[]',
        'signing_algo' => 'string',
        'metadata_policy' => 'string',
        'expire_at' => 'string',
        'created_at' => 'string',
        'created_by' => 'string',
        'renewed_at' => 'string',
        'renewed_by' => 'string',
        'purge_at' => 'string',
        'signing_key' => 'string',
        'statistics' => '\com.vonage.client.model.VonageIntegrationSuite\WebhookStatistics'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id' => 'id',
        'user_id' => 'userId',
        'account_id' => 'accountId',
        'url' => 'url',
        'status' => 'status',
        'events' => 'events',
        'signing_algo' => 'signingAlgo',
        'metadata_policy' => 'metadataPolicy',
        'expire_at' => 'expireAt',
        'created_at' => 'createdAt',
        'created_by' => 'createdBy',
        'renewed_at' => 'renewedAt',
        'renewed_by' => 'renewedBy',
        'purge_at' => 'purgeAt',
        'signing_key' => 'signingKey',
        'statistics' => 'statistics'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id' => 'setId',
        'user_id' => 'setUserId',
        'account_id' => 'setAccountId',
        'url' => 'setUrl',
        'status' => 'setStatus',
        'events' => 'setEvents',
        'signing_algo' => 'setSigningAlgo',
        'metadata_policy' => 'setMetadataPolicy',
        'expire_at' => 'setExpireAt',
        'created_at' => 'setCreatedAt',
        'created_by' => 'setCreatedBy',
        'renewed_at' => 'setRenewedAt',
        'renewed_by' => 'setRenewedBy',
        'purge_at' => 'setPurgeAt',
        'signing_key' => 'setSigningKey',
        'statistics' => 'setStatistics'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id' => 'getId',
        'user_id' => 'getUserId',
        'account_id' => 'getAccountId',
        'url' => 'getUrl',
        'status' => 'getStatus',
        'events' => 'getEvents',
        'signing_algo' => 'getSigningAlgo',
        'metadata_policy' => 'getMetadataPolicy',
        'expire_at' => 'getExpireAt',
        'created_at' => 'getCreatedAt',
        'created_by' => 'getCreatedBy',
        'renewed_at' => 'getRenewedAt',
        'renewed_by' => 'getRenewedBy',
        'purge_at' => 'getPurgeAt',
        'signing_key' => 'getSigningKey',
        'statistics' => 'getStatistics'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const SIGNING_ALGO_HMAC_SHA256 = 'HMAC_SHA256';
    const SIGNING_ALGO_NONE = 'NONE';
    const METADATA_POLICY_NONE = 'NONE';
    const METADATA_POLICY_HEADER = 'HEADER';
    const METADATA_POLICY_BODY = 'BODY';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getEventsAllowableValues()
    {
        return [
            
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getSigningAlgoAllowableValues()
    {
        return [
            self::SIGNING_ALGO_HMAC_SHA256,
            self::SIGNING_ALGO_NONE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getMetadataPolicyAllowableValues()
    {
        return [
            self::METADATA_POLICY_NONE,
            self::METADATA_POLICY_HEADER,
            self::METADATA_POLICY_BODY,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['account_id'] = isset($data['account_id']) ? $data['account_id'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['events'] = isset($data['events']) ? $data['events'] : null;
        $this->container['signing_algo'] = isset($data['signing_algo']) ? $data['signing_algo'] : null;
        $this->container['metadata_policy'] = isset($data['metadata_policy']) ? $data['metadata_policy'] : null;
        $this->container['expire_at'] = isset($data['expire_at']) ? $data['expire_at'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['created_by'] = isset($data['created_by']) ? $data['created_by'] : null;
        $this->container['renewed_at'] = isset($data['renewed_at']) ? $data['renewed_at'] : null;
        $this->container['renewed_by'] = isset($data['renewed_by']) ? $data['renewed_by'] : null;
        $this->container['purge_at'] = isset($data['purge_at']) ? $data['purge_at'] : null;
        $this->container['signing_key'] = isset($data['signing_key']) ? $data['signing_key'] : null;
        $this->container['statistics'] = isset($data['statistics']) ? $data['statistics'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array();
        if (!in_array($this->container['status'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'status', must be one of #{allowed_values}.";
        }
        $allowed_values = array();
        if (!in_array($this->container['events'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'events', must be one of #{allowed_values}.";
        }
        $allowed_values = array("HMAC_SHA256", "NONE");
        if (!in_array($this->container['signing_algo'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'signing_algo', must be one of #{allowed_values}.";
        }
        $allowed_values = array("NONE", "HEADER", "BODY");
        if (!in_array($this->container['metadata_policy'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'metadata_policy', must be one of #{allowed_values}.";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array();
        if (!in_array($this->container['status'], $allowed_values)) {
            return false;
        }
        $allowed_values = array();
        if (!in_array($this->container['events'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("HMAC_SHA256", "NONE");
        if (!in_array($this->container['signing_algo'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("NONE", "HEADER", "BODY");
        if (!in_array($this->container['metadata_policy'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets user_id
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     * @param string $user_id
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets account_id
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     * @param string $account_id
     * @return $this
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets url
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     * @param string $url
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets status
     * @return string[]
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string[] $status
     * @return $this
     */
    public function setStatus($status)
    {
        $allowed_values = array();
        if (!in_array($status, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'status', must be one of ");
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets events
     * @return string[]
     */
    public function getEvents()
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     * @param string[] $events
     * @return $this
     */
    public function setEvents($events)
    {
        $allowed_values = array();
        if (!in_array($events, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'events', must be one of ");
        }
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets signing_algo
     * @return string
     */
    public function getSigningAlgo()
    {
        return $this->container['signing_algo'];
    }

    /**
     * Sets signing_algo
     * @param string $signing_algo
     * @return $this
     */
    public function setSigningAlgo($signing_algo)
    {
        $allowed_values = array('HMAC_SHA256', 'NONE');
        if (!in_array($signing_algo, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'signing_algo', must be one of 'HMAC_SHA256', 'NONE'");
        }
        $this->container['signing_algo'] = $signing_algo;

        return $this;
    }

    /**
     * Gets metadata_policy
     * @return string
     */
    public function getMetadataPolicy()
    {
        return $this->container['metadata_policy'];
    }

    /**
     * Sets metadata_policy
     * @param string $metadata_policy
     * @return $this
     */
    public function setMetadataPolicy($metadata_policy)
    {
        $allowed_values = array('NONE', 'HEADER', 'BODY');
        if (!in_array($metadata_policy, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'metadata_policy', must be one of 'NONE', 'HEADER', 'BODY'");
        }
        $this->container['metadata_policy'] = $metadata_policy;

        return $this;
    }

    /**
     * Gets expire_at
     * @return string
     */
    public function getExpireAt()
    {
        return $this->container['expire_at'];
    }

    /**
     * Sets expire_at
     * @param string $expire_at
     * @return $this
     */
    public function setExpireAt($expire_at)
    {
        $this->container['expire_at'] = $expire_at;

        return $this;
    }

    /**
     * Gets created_at
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets created_by
     * @return string
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     * @param string $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets renewed_at
     * @return string
     */
    public function getRenewedAt()
    {
        return $this->container['renewed_at'];
    }

    /**
     * Sets renewed_at
     * @param string $renewed_at
     * @return $this
     */
    public function setRenewedAt($renewed_at)
    {
        $this->container['renewed_at'] = $renewed_at;

        return $this;
    }

    /**
     * Gets renewed_by
     * @return string
     */
    public function getRenewedBy()
    {
        return $this->container['renewed_by'];
    }

    /**
     * Sets renewed_by
     * @param string $renewed_by
     * @return $this
     */
    public function setRenewedBy($renewed_by)
    {
        $this->container['renewed_by'] = $renewed_by;

        return $this;
    }

    /**
     * Gets purge_at
     * @return string
     */
    public function getPurgeAt()
    {
        return $this->container['purge_at'];
    }

    /**
     * Sets purge_at
     * @param string $purge_at
     * @return $this
     */
    public function setPurgeAt($purge_at)
    {
        $this->container['purge_at'] = $purge_at;

        return $this;
    }

    /**
     * Gets signing_key
     * @return string
     */
    public function getSigningKey()
    {
        return $this->container['signing_key'];
    }

    /**
     * Sets signing_key
     * @param string $signing_key
     * @return $this
     */
    public function setSigningKey($signing_key)
    {
        $this->container['signing_key'] = $signing_key;

        return $this;
    }

    /**
     * Gets statistics
     * @return \com.vonage.client.model.VonageIntegrationSuite\WebhookStatistics
     */
    public function getStatistics()
    {
        return $this->container['statistics'];
    }

    /**
     * Sets statistics
     * @param \com.vonage.client.model.VonageIntegrationSuite\WebhookStatistics $statistics
     * @return $this
     */
    public function setStatistics($statistics)
    {
        $this->container['statistics'] = $statistics;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


