<?php
/**
 * CallsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VonageIntegrationSuite
 *
 * __Vonage® Integration Suite__ powered by __gUnify&trade;__.  --------------------------------
 *
 * OpenAPI spec version: v1
 * Contact: gunifydevops@vonage.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CallsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CallsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for callAnswer
     *
     * Answer call (On supported devices).
     *
     */
    public function testCallAnswer()
    {

    }

    /**
     * Test case for callHold
     *
     * Put call on hold.
     *
     */
    public function testCallHold()
    {

    }

    /**
     * Test case for callTransfer
     *
     * Transfer call.
     *
     */
    public function testCallTransfer()
    {

    }

    /**
     * Test case for callUnold
     *
     * Unhold.
     *
     */
    public function testCallUnold()
    {

    }

    /**
     * Test case for callVMTransfer
     *
     * Send call to voicemail.
     *
     */
    public function testCallVMTransfer()
    {

    }

    /**
     * Test case for createCall
     *
     * Place a call.
     *
     */
    public function testCreateCall()
    {

    }

    /**
     * Test case for destroyCall
     *
     * End a call.
     *
     */
    public function testDestroyCall()
    {

    }

    /**
     * Test case for getCallsCount
     *
     * Get calls count.
     *
     */
    public function testGetCallsCount()
    {

    }

    /**
     * Test case for getRoles
     *
     * Get a call.
     *
     */
    public function testGetRoles()
    {

    }

    /**
     * Test case for listCalls
     *
     * List active calls.
     *
     */
    public function testListCalls()
    {

    }

}
